# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 한규빈
title: 자바 백엔드 개발자
email: rbsks147@gmail.com
website: https://rbsks.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: rbsks
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
    Java, Spring 기반의 3년 차 자바 백엔드 개발자로 현재는 전세계 200여 개국으로 간편하게 송금이 가능한 해외송금 서비스를 제공하는 회사에서 기업 송금 및 정산을 주요 업무로 하고 있습니다.  

      
    - 새로운 기술 습득하기 위해 꾸준히 개발 서적 읽기와 공부한 내용을 블로그에 작성합니다.
    - 사이드 이펙트를 미리 대비하여 꼼꼼히 설계하기를 노력하고 테스트 코드를 열심히 작성합니다.
    - 더 좋은 방향으로 문제를 해결하기 위해 코드를 검토하고 리팩토링을 실천합니다.
    
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: 한패스
        sub_title: 기업 송금 개발팀 / 사원
        caption: 2022.12 ~ 현재 재직중
        link: https://www.hanpass.com/
        quote: >
          전세계 200여 개국으로 간편하게 송금이 가능한 해외송금 서비스 제공
        description: | # this will include new lines to allow paragraphs
          <mark>Spring Boot, </mark> <mark>Spring Data JPA, </mark> <mark>Thymeleaf, </mark> <mark>RabbitMQ, </mark> <mark>Jenkins, </mark> <mark>Nginx, </mark> <mark>MariaDB</mark>  
          - __JAVA 11에서 TLS 1.3 인증 실패 이슈로 인한 빌드 버전 업데이트 2023.11 ~ 2023.11__  
            - JAVA 11에서 TLS 1.3 인증 시 동일한 PSK 사용으로 인해 TLS 인증이 실패하는 이슈가 발생하여 예외 메시지를 파악 후 JAVA 11.0.3 미만 버전에서 발생하는 이슈임을 확인.
            운영 서버의 자바 버전 확인 결과 JAVA 11 EA로 확인이 되어 이슈가 해결된 JAVA 11.0.3 이상으로 빌드 버전을 업데하여 TLS 1.3 인증 실패하는 이슈 해결.
          - __어드민 메인 페이지 송금 현황 차트 개발 2023.09 ~ 2023.09__  
            - 월별 송금 총 금액과 송금 건수 현황 차트 개발.
            - 월별 국가, 기업 송금 이용 고객, 통화 별 송금 금액과 송금 건수 top 5 현황 차트 개발.
          - __통화 별 다건 송금 개발 2023.05 ~ 2023.09__  
            - 통화 별로 수취인의 정보를 입력할 수 있는 엑셀 템플릿에 대한 다운로드 기능을 제공하고 기업송금 고객은 다운로드한 엑셀 템플릿을 사용하여 여러 명의 수취인의 정보를 입력 후 엑셀을 업로드하여 한 번에 최대 100명의 수취인에게 송금을 할 수 있는 기능 개발.  
            - 싱글 스레드로 송금 요청을 했던 방식에서 멀티 스레드로 송금 요청을 하는 방식으로 변경 후 100건 송금 시 약 50s -> 10s로 송금 요청 시간 단축.
            - 기존 한 건의 기업 송금만 가능했던 시스템에서 다 건 송금을 개발하여 한 번에 여러 건을 송금 할 수 있기 때문에 위와 같은 번거로운 상황이 줄어들어 사용자 경험이 증가.
          - __기업 송금 정산 개발 2023.04 ~ 2023.05__  
            - 기업 송금의 일일 총 송금 건, 총 송금 금액, 총 수수료 금액, 총 환불 금액, 이윤 금액 정산 개발하여 사업 팀에서 수기로 정산했던 것을 자동화하여 어드민 페이지에 제공하고 엑셀 파일로 다운로드할 수 있는 기능을 제공.

      - title: 에픽브레인     
        sub_title: 개발팀 / 사원
        caption: 2020.14 ~ 2022.04
        link: https://www.autopus.co.kr/
        quote: >
          숙박, 액티비티 등 실시간 예약 및 관리를 할 수 있는 오토퍼스 서비스와 골프 스튜디오 예약과 프로 골퍼의 스케줄을 확인하고 실시간 예약을 할 수 있는 구스트 서비스를 제공
        description: | # this will include new lines to allow paragraphs
          <mark>Spring Framework, </mark> <mark>Mybatis, </mark> <mark>JSP, </mark> <mark>AWS, </mark> <mark>MySQL</mark>  
          - __골프 레슨, 스튜디오 예약 관리 플랫폼 [구스트 서비스](https://goost.co/) 개발 참여__ 
          - __골프 레슨 요청 게시판 개발 2022.03 ~ 2022.04__
            - 유저가 골프 레슨 요청 게시판에 집중적으로 받고 싶은 레슨, 프로 성별, 레슨 위치, 희망 가격 등 을 작성할 수 있는 게시판 개발하여 유저가 골프 레슨을 받기 위해 지역 및 프로를 검색하는 번거로움을 줄여 사용자 경험을 증가.
          - __골프 레슨 리뷰 개발 2021.07 ~ 2021.08__
            - 유저가 받은 골프 레슨에 대한 후기와 평점을 작성할 수 있는 기능 개발.

  - title: Project
    layout: list
    content:
      - layout: left
        title: arffy
        caption: 2023.05 ~ 현재
        link: https://arffy.store/
          
        description: | # this will include new lines to allow paragraphs
          20세기 유럽의 빈티지 조명과 소품을 판매하는 브랜드 arffy의 온라인 스토어입니다.    

            
          팀 구성: Back-End 2명, Front-End 1명  
          사용 기술: Spring Boot, Spring Data JPA, AWS, Docker, Nginx, MySQL    
            
          담당 기능
          - 쇼핑몰 관리자 서버 개발
          - 이메일 발송 및 슬랙 메시지 전송 서버 개발
          
      - title: 로켓단의 한국 정복
        caption: 2022.10 ~ 2022.11
          
        description: | # this will include new lines to allow paragraphs
          [로켓단의 한국 정복 깃허브](https://github.com/TeamRocketDan)    
          [로켓단의 한국 정복 포트폴리오](https://fringe-actress-f29.notion.site/Rocketdan-Portfolio-0718b0cd27104add8eed1be8e46da887?pvs=4)  
          가고 싶은 여행의 일정과 지역을 포함한 채팅방을 개설해 동행을 모을 수 있는 서비스입니다.  
          인기 있는 피드와 지역 위치(시도, 구)로 피드들을 볼 수 있어 대략적인 지역의 볼 거리들을 알아볼 수 있고 본인의 피드를 정리하는 페이지를 통해 여행에서 느꼈던 행복한 추억을 공유하고 저장할 수 있습니다.     

            
          팀 구성: Back-End 4명, Front-End 2명  
          사용 기술: Spring Boot, Spring Data JPA, RabbitMQ, AWS, Docker, Jenkins, Nginx, MySQL, MongoDB, Redis     
            
          담당 기능
          - 시도, 구 리스트에 Redis cache 적용
          - 피드, 댓글 리스트 쿼리 개선 1s ~ 2s  100ms 이하
          - jenkins pipeline을 통한 배포 자동화
          - AWS Load Balancing을 활용하여 트래픽 분산
          
      - title: WorkDuo
        caption: 2022.08 ~ 2022.10
          
        description: | # this will include new lines to allow paragraphs
          [WorkDuo 깃허브](https://github.com/WorkDuo/WorkDuo_dev)    
          [WorkDuo 포트폴리오](https://alive-tern-b83.notion.site/WorkDuo-Portfolio-bddf628d3f394cc2b17b35b2587bee76?pvs=4)  
          구성원들과 운동 모임을 개설하여 같이 운동을 할 수 있도록 도와주는 서비스입니다.  
          유저는 개인 피드에 운동 일지를 기록할 수 있고 그룹에 가입하여 그룹 피드를 통해 구성원들과 소통할 수 있습니다. 

            
          팀 구성: Back-End 2명
          사용 기술: Spring Boot, Spring Data JPA, Redisson, AWS, MySQL, Redis     
            
          담당 기능
          - 모임의 정원이 초과하지 않도록 Redisson 분산락 적용
          - 유저 일정을 확인하여 중복 모임 참여/생성 제한   
        
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
